### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by ghost** [NKN1396/Discord-EmojiToRole#2]
Hello! Is there anyway to put the config.json to be a .env?

**Comment by AndrewDaGuy** [comment]
> Hello! Is there anyway to put the config.json to be a .env?

I don't think you can make the entire config file into a `.env`, but I created a version where the token config is one (didn't test but should work): https://github.com/AndrewDaGuy/Discord-EmojiToRole/tree/env

**Comment by SpreeHertz** [comment]
You'll have to change in some stuff. 

First, you have to install the `dotenv` package, and change `token` to `process.env.token` in index.js.

If you don't mind me asking, why do you want to change it to `.env`? It works the same 🤷‍♀️
